updates

diff --git a/bin/ftm b/bin/ftm
--- a/bin/ftm
+++ b/bin/ftm
@@ -40,8 +40,8 @@ SESSION_ICON="${SESSION_ICON:-󰢩}"
 
 # -- check for our dependencies..
 [[ -n $TMUX ]] && TMUX_RUNNING="running" || TMUX_RUNNING="not running"
-(command -v fzf &> /dev/null) && FZF_FOUND="installed" || FZF_FOUND="not installed"
-(command -v sk &> /dev/null) && SKIM_FOUND="installed" || SKIM_FOUND="not installed"
+(command -v fzf &>/dev/null) && FZF_FOUND="installed" || FZF_FOUND="not installed"
+(command -v sk &>/dev/null) && SKIM_FOUND="installed" || SKIM_FOUND="not installed"
 [[ -d "$TMUX_LAYOUTS" ]] && layouts_dir="$TMUX_LAYOUTS" || layouts_dir=""
 
 # -- friendly help if -h option given
@@ -71,30 +71,30 @@ fi
 while getopts "phs:" OPTION; do
   case $OPTION in
 
-    p)
-      export TMUX_POPUP=1
-      POPUP="true"
-      ;;
+  p)
+    export TMUX_POPUP=1
+    POPUP="true"
+    ;;
 
-    h)
-      __help
-      ;;
-    s)
-      SAVED_SESSION_NAME="$OPTARG"
-      echo "Saving session with session name: $OPTARG"
-      exit 0
-      ;;
+  h)
+    __help
+    ;;
+  s)
+    SAVED_SESSION_NAME="$OPTARG"
+    echo "Saving session with session name: $OPTARG"
+    exit 0
+    ;;
 
-    \?)
-      # NOTE: this covers the case where an optarg may not be provided
-      # and will exit errored
-      echo "Invalid Option: -$OPTARG" 1>&2
-      exit 1
-      ;;
-    :)
-      echo "Invalid Option: -$OPTARG requires an argument" 1>&2
-      exit 1
-      ;;
+  \?)
+    # NOTE: this covers the case where an optarg may not be provided
+    # and will exit errored
+    echo "Invalid Option: -$OPTARG" 1>&2
+    exit 1
+    ;;
+  :)
+    echo "Invalid Option: -$OPTARG requires an argument" 1>&2
+    exit 1
+    ;;
   esac
 done
 # shift $((OPTIND - 1))
@@ -155,14 +155,14 @@ function try_session() {
   session="$(echo "$1" | sed '/^$/d')"
 
   # FIXME: zoxide doesn't cut it completely; need to fuzzy find all folders in `$CODE`
-  cwd=$(zoxide query "$session" 2> /dev/null || fd -1 "$session" "$CODE")
+  cwd=$(zoxide query "$session" 2>/dev/null || fd -1 "$session" "$CODE")
 
   # backup plan: use dotfiles dir if nothing found
   if [[ -z "$cwd" ]]; then
     cwd="$DOTS"
   fi
 
-  to_session "$session" 2> /dev/null || new_session "$session" "${cwd}"
+  to_session "$session" 2>/dev/null || new_session "$session" "${cwd}"
 }
 
 function fuzzy_find() {
@@ -267,14 +267,14 @@ function fuzzy_find() {
         --bind="${CTRL_R_rename_session_bind}" \
         \
         --bind="enter:replace-query+print-query" \
-        --preview="${preview_cmd}" \
-        --preview-window="bottom:65%:nowrap" \
         --pointer=' ' \
         --marker='󰛄 ' \
         --print-query \
         --exit-0 \
         --tac
   )"
+  # --preview="${preview_cmd}" \
+  # --preview-window="bottom:65%:nowrap" \
 
   echo "$selected_session"
   try_session "$selected_session"
